### ISSUE TITLE
libghdl is unavailable

### ISSUE THREAD

**Issue by SethGower** [ghdl/ghdl-language-server#8]
The link to `libghdl` is broken/it was removed from github. So I can't install due to that. Any suggestions?

**Comment by 1138-4EB** [comment]
Hi @SethGower! If you mean the following step in the README:

> Install libghdl. After building GHDL, a tarball named libghdl-py.tgz should be available at the root. Install it with pip install libghdl-py.tgz.

That's because libghdl-py can be directly installed now (see ghdl/ghdl#848). You just need to get it from https://github.com/ghdl/ghdl/tree/master/python. For example:

``` bash
mkdir libghdl-py
cd libghdl-py
curl -fsSL https://codeload.github.com/ghdl/ghdl/tar.gz/master | tar xzf - --strip-components=2 ghdl-master/python
pip3 install .
```

However, note that the 'master' branch is broken ATM (see #7).

Furthermore, there are some ready-to-use docker images:

- `ghdl/ext:ls-debian`: includes GHDL, libghdl, libghdl-py and the language server. The vscode extension can be installed with a script available in `/opt/ghdl/`.
- `ghdl/ext:ls-ubuntu`: the same, but based on Ubuntu Bionic, instead of Debian Stretch.
- `ghdl/ext:ls-vunit-gtkwave`: the same as the debian image, but includes VUnit and GtkWave too.

The dockerfiles are available at https://github.com/ghdl/docker/tree/master/dockerfiles/ext.

This is a screencast about how to use these docker images with Visual Studio Code's 'Remote - Containers' extension: https://files.gitter.im/ghdl1/Lobby/qboA/ghdl-vsce.gif.gif
